export type Wordlist = string[]
export { wordlist as wordlistChineseSimplified } from "@scure/bip39/wordlists/simplified-chinese"
export { wordlist as wordlistChineseTraditional } from "@scure/bip39/wordlists/traditional-chinese"
export { wordlist as wordlistCzech } from "@scure/bip39/wordlists/czech"
export { wordlist as wordlistEnglish } from "@scure/bip39/wordlists/english"
export { wordlist as wordlistFrench } from "@scure/bip39/wordlists/french"
export { wordlist as wordlistItalian } from "@scure/bip39/wordlists/italian"
export { wordlist as wordlistJapanese } from "@scure/bip39/wordlists/japanese"
export { wordlist as wordlistKorean } from "@scure/bip39/wordlists/korean"
export { wordlist as wordlistSpanish } from "@scure/bip39/wordlists/spanish"